# Generated by Django 5.2.1 on 2025-06-02 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_autor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autores',
        ),
    ]
